# suppress inspection "UnusedProperty" for the whole file

kP_heading=0.06
kP_position=0.035
positionTolerance=1
headingTolerance=1

# Camera
CameraPosition_right=0
CameraPosition_forward=0
CameraPosition_yaw=0

# GoBilda Pinpoint odometry pods offsets in cm. These values are tuned for 3110-0002-0001 Product Insight #1
# https://www.gobilda.com/pinpoint-odometry-computer-imu-sensor-fusion-for-2-wheel-odometry/
pinpoint_xOffset=3.6
pinpoint_yOffset=-10.8
pinpoint_yEncoderDirection=R

#Dimensions

ROBOT_WHEELBASE_WIDTH=42
ROBOT_WHEELBASE_LENGTH=34
GATE_OPENING_POINT_X=

### RoadRunner Parameters

# drive model parameters
inPerTick = 0.001989225031
lateralInPerTick = 0.0015765088698323675
trackWidthTicks = 5497.435244918532

# feedforward parameters (in tick units)
kV = 0.000258192053543453
kS = 0.8502231188492493
kA = 0.000043

# path profile parameters (in cm)
maxWheelVel = 150
minProfileAccel = -70
maxProfileAccel = 150

# turn profile parameters (in degrees)
maxAngVel = 180
maxAngAccel = 180

# path controller gains
axialGain = 12
lateralGain = 10.0
headingGain = 7.0

axialVelGain = 0
lateralVelGain = 2
headingVelGain = 1.4

# Programs
# B or F - Switch to shooting from Back or Front. Also, where do we start from
# 1, 2, 3 - collect from the spike, where #1 is the closest to the Back
# 0 - collect from the human loading zone (farthest from the goal)
# 4 - open and collect directly from the ramp
# / - Shoot now. By default, it shoots right before it needs to collect next load and we already have one loaded

ProgramCatalogue=BPF2R31:Push bot,\
F2R31:North,\
B30000:Last spike and box cycling,\
F2413:All spikes + ramp
