# suppress inspection "UnusedProperty" for the whole file

# PANELS ===========================================================================================
PANELS_ENABLED=true
CAMERA_STREAM_ENABLED=true

# CONTROLS =========================================================================================
# Teleop stick sensitivity
ROTATIONAL_GAIN=30
POSITIONAL_GAIN=80


# Drive controllers ================================================================================
heading_K=0.024, 0.015, 0.001, 0.3
drive_K=0.026, 0.002, 0.003, 0.3
drive_K2=0.055, 0.001, 0.0086, 0.3
translational_K=0.033, 0.0, 0.0035, 0.3

positionTolerance=3
headingTolerance=3
artifactStrafeTolerance=2

# PINPOINT =========================================================================================
pinpoint_xOffset=3.6
pinpoint_yOffset=-10.8
pinpoint_yEncoderDirection=R
# After 20 CCW full circles reported heading angle was +5 degrees. Should be 0. Original yawScalar of a device is 1.0021557
# Formula: newYawScalar = oldYawScalar * (actual_rotation / reported_rotation)
pinpoint_yawScalar=1.001348980527

# SHOOTER ==========================================================================================
SHOOTER_FREE_QUOTIENT = 0.386772
SHOOTER_DISTANCE_QUOTIENT = 0.001165
SHOOTER_POWER_ADJUST = 1.0
SHOOTER_PID = 35
SHOOTER_ANGLE_CORRECTION=0
SHOOTER_ERROR_MARGIN=0.04

LATCH_SERVO_OPEN_POSITION = 0.0
LATCH_SERVO_CLOSED_POSITION = 0.65
LATCH_SERVO_DIRECTION = F
LATCH_SERVO_RUN_TIME_MS=500

PUSHER_SERVO_OPEN_POSITION = 0.95
PUSHER_SERVO_CLOSED_POSITION = 0.0
PUSHER_SERVO_ACTIVATION_DELAY_MS = 25
PUSHER_SERVO_ACTIVATION_DURATION_MS = 350
PUSHER_SERVO_RELEASE_THRESHOLD_MA = 1800

LOWER_SENSOR_THRESHOLD=7

SHOOTING_TIME_MAX_SECONDS = 2.0

# LIMELIGHT ================================================
Camera_angleRange=70

# INTAKE ===========================================================================================
INTAKE_CUTOFF_DELAY_MS=300


# TURRET  ==========================================================================================
# Possible turret modes:
# OFF: Turret is free floating. Controller doesn't do anything,
# FIXED: Turret is fixed aligned with robot's heading,
# FOLLOW: Turret continuously aiming at the goal,
# SHOOTING: Turret aims at the goal only for shooting and aligned with robot's heading otherwise
TURRET_MODE=SHOOTING

#TURRET_MOTOR_PIDF=0.038,0.5,0.0012
#TURRET_MOTOR_PIDF=0.015,0.8,0.0028
TURRET_MOTOR_PIDF=0.007
TURRET_MOTOR_DIRECTION=R
TURRET_MIN_ANGLE=-285
TURRET_MAX_ANGLE=100
TURRET_TICKS_LOOKAHEAD=2
TURRET_CENTER_OFFSET=2.592
NAVX_yawScalar=0.9549010936


# DIMENSIONS =======================================================================================
ROBOT_LENGTH=43.9792
ROBOT_WIDTH=36.8144
ROBOT_FRONT_OFFSET=26.5398
ROBOT_BACK_OFFSET=17.4956
ROBOT_WHEELBASE_WIDTH=30.575
ROBOT_WHEELBASE_LENGTH=21.600

# LOCATIONS ========================================================================================
GOAL=-174,158

BOX_APPROACH=150,123,90
BOX_SCOOP=156,150,90
BOX_SCOOP_SPEED=1.0

BOX_SCOOP_OBSERVATION_P1=E1:90
BOX_SCOOP_OBSERVATION_P2=E2:90

NORTH_START=-165,60,0
SOUTH_START=160,38,90

OPEN_RAMP_COLLECT=28,144,110
OPEN_RAMP_COLLECT_APPROACH=26,136,111

OPEN_RAMP=19,135,90
OPEN_RAMP_APPROACH=19,110,90

OPEN_RAMP_SPEED=0.7
COLLECT_FROM_OPEN_RAMP=47,152,90
COLLECT_FROM_OPEN_RAMP_APPROACH=47,100,90

# SHOOTING ZONE NAVIGATION =========================================================================
minGoalDistance=140
zoneSafetyMargin=15

# Programs =========================================================================================
# B or F - Switch to shooting from Back or Front. Also, where do we start from
# P - Push alliance partner but out of launch zone in case they don't have auto
# 1, 2, 3 - collect from the spike, where #1 is the closest to the Back
# 0 - collect from the human loading zone (farthest from the goal)
# 4 - open and collect directly from the ramp
# / - Shoot now. By default, it shoots right before it needs to collect next load and we already have one loaded

ProgramCatalogue=BPF2R31:Push bot,\
F2R31:North,\
B1VVVVVVVVVVV:Visual,\
B10000:Last spike and box cycling,\
F2413:All spikes + ramp
